name: rutero_server
description: Servidor HTTP para la base de datos
version: 0.0.1
author: Diego Gallego <diego.gallego@flexolumens.co>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  html: ^0.14.0+3
  convert: ^2.1.1
  tuple: ^1.0.3
  basic_utils: ^2.5.4
  http: ^0.12.1
  path: ^1.7.0
  archive: ^2.0.13
  mongo_dart: ^0.4.0
  
  
dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0